/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author brayan
 */
public class InterfazLogin extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public InterfazLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.jpg"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JLabelIcono = new javax.swing.JLabel();
        JButtonSalir = new javax.swing.JButton();
        JLabelUsuario = new javax.swing.JLabel();
        JLabelContraseña = new javax.swing.JLabel();
        JTextFieldU = new javax.swing.JTextField();
        JPasswordFieldC = new javax.swing.JPasswordField();
        JButtonIniciar = new javax.swing.JButton();
        JLabelError = new javax.swing.JLabel();
        JLabelFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.jpg"))); // NOI18N
        JLabelIcono.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(JLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, 220));

        JButtonSalir.setBackground(new java.awt.Color(249, 248, 248));
        JButtonSalir.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonSalir.setText("Salir");
        JButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JButtonSalirMouseEntered(evt);
            }
        });
        JButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalirActionPerformed(evt);
            }
        });
        JButtonSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JButtonSalirKeyPressed(evt);
            }
        });
        getContentPane().add(JButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 90, 30));

        JLabelUsuario.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        JLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        JLabelUsuario.setText("Usuario  : ");
        getContentPane().add(JLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 30));

        JLabelContraseña.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        JLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        JLabelContraseña.setText("Contraseña  :");
        getContentPane().add(JLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 40));

        JTextFieldU.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        JTextFieldU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldUActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFieldU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 290, 25));

        JPasswordFieldC.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        JPasswordFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordFieldCActionPerformed(evt);
            }
        });
        getContentPane().add(JPasswordFieldC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 290, 25));

        JButtonIniciar.setBackground(new java.awt.Color(249, 248, 248));
        JButtonIniciar.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonIniciar.setText("Iniciar Seción");
        JButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 270, 30));

        JLabelError.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        JLabelError.setForeground(new java.awt.Color(244, 58, 58));
        getContentPane().add(JLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 440, 20));

        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JButtonSalirActionPerformed

    private void JTextFieldUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldUActionPerformed

    private void JPasswordFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordFieldCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordFieldCActionPerformed

    private void JButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonIniciarActionPerformed
        String usuario = JTextFieldU.getText();
        String contraseña = new String(JPasswordFieldC.getPassword());
        
        if(validateLogin(usuario, contraseña)&&!usuario.isBlank()&&!contraseña.isBlank()) {  
            JLabelError.setText("Pasando al menú principal...");
            systemSleep();
            
            this.setVisible(false);
            InterfazMenu interfaMenu = new InterfazMenu();
            interfaMenu.setVisible(true);
        }
        else {
            JLabelError.setText("Usuario o contraseña erroneos. Y/O campo(s) en blanco"); 
            if(!usuario.isBlank()&&!contraseña.isBlank()) {
                //Se guarda en un CSV
            }
        }
    }//GEN-LAST:event_JButtonIniciarActionPerformed

    private void JButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonSalirMouseClicked

    }//GEN-LAST:event_JButtonSalirMouseClicked

    private void JButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonSalirMouseEntered

    }//GEN-LAST:event_JButtonSalirMouseEntered

    private void JButtonSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JButtonSalirKeyPressed

    }//GEN-LAST:event_JButtonSalirKeyPressed

    private boolean validateLogin(String usuario, String contraseña){
        return true;
    }
    
     private void systemSleep(){
        try {
            TimeUnit.SECONDS.sleep(2);
        } catch (InterruptedException ex) {
            Logger.getLogger(InterfazMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonIniciar;
    private javax.swing.JButton JButtonSalir;
    private javax.swing.JLabel JLabelContraseña;
    private javax.swing.JLabel JLabelError;
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JLabel JLabelIcono;
    private javax.swing.JLabel JLabelUsuario;
    private javax.swing.JPasswordField JPasswordFieldC;
    private javax.swing.JTextField JTextFieldU;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
