/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author migue
 */
public class InterfazGuardarAlu extends javax.swing.JFrame {

    /**
     * Creates new form Guardar
     */
    public InterfazGuardarAlu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonRegresar = new javax.swing.JButton();
        JButtonSalir = new javax.swing.JButton();
        JButtonGuardarTodos = new javax.swing.JButton();
        JButtonGuardarTodosLM = new javax.swing.JButton();
        JButtonGuardar1Alu = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButtonRegresar.setBackground(new java.awt.Color(249, 248, 248));
        JButtonRegresar.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonRegresar.setText("Regresar");
        JButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 50));

        JButtonSalir.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonSalir.setText("Salir");
        JButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 140, 50));

        JButtonGuardarTodos.setBackground(new java.awt.Color(249, 248, 248));
        JButtonGuardarTodos.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonGuardarTodos.setText("Guardar todo el alumnado");
        JButtonGuardarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonGuardarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 270, 50));

        JButtonGuardarTodosLM.setBackground(new java.awt.Color(249, 248, 248));
        JButtonGuardarTodosLM.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonGuardarTodosLM.setText("Guardar todas las materias");
        JButtonGuardarTodosLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardarTodosLMActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonGuardarTodosLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 270, 50));

        JButtonGuardar1Alu.setBackground(new java.awt.Color(249, 248, 248));
        JButtonGuardar1Alu.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        JButtonGuardar1Alu.setText("Guardar un alumno");
        JButtonGuardar1Alu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardar1AluActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonGuardar1Alu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 270, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/muro.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 768, 664));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JButtonSalirActionPerformed

    private void JButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegresarActionPerformed
        this.setVisible(false);
        InterfazMenu interfazMenu = new InterfazMenu();
        interfazMenu.setVisible(true);
    }//GEN-LAST:event_JButtonRegresarActionPerformed

    private void JButtonGuardarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardarTodosActionPerformed
        //alumnado.to_csv();
    }//GEN-LAST:event_JButtonGuardarTodosActionPerformed

    private void JButtonGuardarTodosLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardarTodosLMActionPerformed
        //planMadre.toCsv();
    }//GEN-LAST:event_JButtonGuardarTodosLMActionPerformed

    private void JButtonGuardar1AluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardar1AluActionPerformed
        /*int pos = alumnado.buscar(alumnado);
        alumnado.alumnado.get(pos).toCsv(alumnado.alumnado.get(pos)); */
    }//GEN-LAST:event_JButtonGuardar1AluActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGuardarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGuardarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGuardarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGuardarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGuardarAlu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonGuardar1Alu;
    private javax.swing.JButton JButtonGuardarTodos;
    private javax.swing.JButton JButtonGuardarTodosLM;
    private javax.swing.JButton JButtonRegresar;
    private javax.swing.JButton JButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
